on: [push, pull_request]
name: Linux, macOS and Windows
env:
  MAGEFILE_VERBOSE: true
  GOBIN: ${{ github.workspace }}/.bin
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      shell: bash
      run: |
        go install github.com/magefile/mage
        .bin/mage test
